### PR TITLE
Remove ES6 Syntax

### PR DESCRIPTION
**Pull request by Alamantus**
Remove ES6 template strings & arrow functions to help with issue #31 

`choojs/object-change-callsite` dependency will also need to be updated because it also still has the same issue (uses ES6 Proxy without a polyfill). I'll be working on a pull request for that next.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
sweet! I don't know if object-change-callsite is polyfillable but we can always make it a noop when Proxy is unavailable.

CI is failing because of some style issues, could you fix those? running `npm test` will list them.

**Comment by Alamantus** [comment]
@goto-bus-stop I didn't notice the style lint—I just updated the style issues :)

As for Proxy, would this proxy polyfill work: https://github.com/GoogleChrome/proxy-polyfill
I've never used proxy, but I was planning on just dropping that in if Proxy doesn't exist.

**Comment by goto-bus-stop** [comment]
thanks!

that polyfill doesn't support properties being added or deleted unfortunately, which are things you _can_ do with a choojs state object.

**Comment by goto-bus-stop** [comment]
:package: 2.5.1

**Pull request merged**
