### PR TITLE
expose .copy method

### PR DESCRIPTION
**Pull request by jakeburden**
ref: #4 

allows for exposing a `window.choo.copy` method the lets users copy state to clipboard.

example:
```js
window.addEventListener('keyup', function (e) {
  // press 'c' to copy current state to clipboard
  if (e.keyCode === 67) {
    window.choo.copy(window.choo.state)
  }
})
```

Note: it turns out document.execCommand('copy') [only works with user gestured events such as click and keyup](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard#Writing_to_the_clipboard).  Thats the reason why the example has an event listener. I had an idea too, it might be useful for there to be a choo-expose-ui that creates a nice button for choo devs to click and get application state in the clipboard.  Would love to get your thoughts!

Cheers!

### CODE REVIEW

**Comment by jakeburden** [comment]
oh this works with plucker too!

```js
window.addEventListener('keyup', function (e) {
  // press 'c' to copy value to clipboard
  if (e.keyCode === 67) {
    var object = { hello: { world: { lorem: 'ipsum' } } }
    window.choo.copy('hello.world.lorem', object)
  }
})
```

will copy `'ipsum'` to the clipboard

**Comment by yoshuawuyts** [comment]
Nice work! Lil nit on the API tho, would be cool if _this just worked™_:
```js
window.choo.copy()                 // => copied the whole state
window.choo.copy('state.form.foo') // => copied a specific path
```

**Comment by yoshuawuyts** [comment]
Also probably worth filtering out any functions b/c if they're stringified you get the weird `[Object function]` style blocks haha

**Comment by jakeburden** [comment]
hey @yoshuawuyts :wave: I just pushed up a change to this branch that lets `.copy()` get the whole state, it also checks if a function was passed in and if so, ignores it and just copies the whole state.

Not done yet though, I'll get this part working next:

```
window.choo.copy('state.form.foo') // => copied a specific path
```

**Comment by jakeburden** [comment]
just pushed up a change that lets `window.choo.copy('state.form.foo')` copy choo state at a specific path to clipboard :)

**Comment by jakeburden** [comment]
howdy @yoshuawuyts :wave:

are there any outstanding features of this api thats left to complete?

**Review by yoshuawuyts — APPROVED** [review]
awesome, thank you!

**Comment by yoshuawuyts** [comment]
`v1.3.0` - added you as an owner too! :sparkles:

**Pull request merged**
